// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZ-i9Lnmh813S_YnMDFQT7HEhA6eBrm4',
    appId: '1:568535607274:web:5f52f1ff519cf45dd17493',
    messagingSenderId: '568535607274',
    projectId: 'batme-wallet',
    authDomain: 'batme-wallet.firebaseapp.com',
    storageBucket: 'batme-wallet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGMMltGUfRdtgJHCwtx-3z2s-T-8YPRt8',
    appId: '1:568535607274:android:d7fbc0540c2712f7d17493',
    messagingSenderId: '568535607274',
    projectId: 'batme-wallet',
    storageBucket: 'batme-wallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG9d4PtMXgqhawOV5K238lttDsX6EreRM',
    appId: '1:568535607274:ios:7edf56663122b870d17493',
    messagingSenderId: '568535607274',
    projectId: 'batme-wallet',
    storageBucket: 'batme-wallet.firebasestorage.app',
    iosBundleId: 'com.example.betappadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG9d4PtMXgqhawOV5K238lttDsX6EreRM',
    appId: '1:568535607274:ios:7edf56663122b870d17493',
    messagingSenderId: '568535607274',
    projectId: 'batme-wallet',
    storageBucket: 'batme-wallet.firebasestorage.app',
    iosBundleId: 'com.example.betappadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZ-i9Lnmh813S_YnMDFQT7HEhA6eBrm4',
    appId: '1:568535607274:web:d6404a75801d24dcd17493',
    messagingSenderId: '568535607274',
    projectId: 'batme-wallet',
    authDomain: 'batme-wallet.firebaseapp.com',
    storageBucket: 'batme-wallet.firebasestorage.app',
  );
}
